import Head from "next/head";
import { NextPage } from "next/types";
import { Container } from "../src/components/Container";
import { Header } from "../src/components/Header";

const ErrorPage: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Home | Rodolfo Vieira - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <h1 style={{ color: "white", marginTop: "200px", marginLeft: "200px" }}>
        404 - Page Not Found
      </h1>
      <p style={{ color: "white", padding: " 0 200px" }}>
        Ooops, it looks like this page does not exist, try again another link on
        the header above!
      </p>
      {/* To Do: Add Footer */}
    </Container>
  );
};

export default ErrorPage;
